runtime: nodejs18

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|json|txt))
    static_files: build/\1
    upload: build/(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|json|txt))

  - url: /.*
    static_files: build/index.html
    upload: build/index.html